version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "tuesday"
    target-branch: "main"
    ignore:
      # ignore all patch updates since we are using ~=
      # this does not work for security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
