name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Uncomment the following line if using PERSONAL_TOKEN
          # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # Uncomment and modify if using a custom domain
          # CUSTOM_DOMAIN: optionaldomain.com
          # Uncomment and modify if your mkdocs.yml is not in the root directory
          # CONFIG_FILE: folder/mkdocs.yml
          # Uncomment and modify if you need to install extra packages
          # EXTRA_PACKAGES: build-base
          # Uncomment and modify if using GitHub Enterprise
          # GITHUB_DOMAIN: github.myenterprise.com
          # Uncomment and modify if you have a requirements.txt file for MkDocs plugins
          REQUIREMENTS: requirements.txt
